### ISSUE TITLE
No longer works with SDC7 :(

### ISSUE THREAD

**Issue by kigster** [evantahler/smartdc-cost#1]
Any plans to upgrade smartdc-cost with the new joyent SDC7 api and new images / pricing? :)

**Comment by evantahler** [comment]
https://github.com/evantahler/smartdc-cost/pull/2

I'll `npm` it later today

Note the readme about the ENV changes from Joyent

**Comment by kigster** [comment]
Rocking!!! :)

**Comment by evantahler** [comment]
now we just need to get @joyent to add this to the real sdc commands
